/*
 * Created on 2 Nov 2017 ( Time 21:21:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package imta.modele.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import imta.modele.bean.jpa.ArticleEntity;
import imta.modele.persistence.commons.jpa.GenericJpaService;
import imta.modele.persistence.commons.jpa.JpaOperation;
import imta.modele.persistence.services.ArticlePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Article" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ArticlePersistenceJPA extends GenericJpaService<ArticleEntity, Integer> implements ArticlePersistence {

	/**
	 * Constructor
	 */
	public ArticlePersistenceJPA() {
		super(ArticleEntity.class);
	}

	@Override
	public ArticleEntity load( Integer id ) {
		return super.load( id );
	}

	@Override
	public boolean delete( Integer id ) {
		return super.delete( id );
	}

	@Override
	public boolean delete(ArticleEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("ArticleEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

}
