/*
 * Created on 3 Nov 2017 ( Time 09:39:01 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package imta.modele.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;

import imta.modele.bean.jpa.UtilisateurEntity;
import imta.modele.persistence.commons.jpa.GenericJpaService;
import imta.modele.persistence.commons.jpa.JpaOperation;
import imta.modele.persistence.services.UtilisateurPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Utilisateur" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class UtilisateurPersistenceJPA extends GenericJpaService<UtilisateurEntity, String> implements UtilisateurPersistence {

	/**
	 * Constructor
	 */
	public UtilisateurPersistenceJPA() {
		super(UtilisateurEntity.class);
	}

	@Override
	public UtilisateurEntity load( String identifiant ) {
		return super.load( identifiant );
	}

	@Override
	public boolean delete( String identifiant ) {
		return super.delete( identifiant );
	}

	@Override
	public boolean delete(UtilisateurEntity entity) {
		if ( entity != null ) {
			return super.delete( entity.getIdentifiant() );
		}
		return false ;
	}

	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("UtilisateurEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

	@Override
	public long deleteAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("UtilisateurEntity.deleteAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		execute(operation);
	}
}
