
/*
 * Created on 2 Nov 2017 ( Time 21:21:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package imta.modele.mock;

import java.util.LinkedList;
import java.util.List;

import imta.modele.bean.jpa.UtilisateurEntity;
import imta.modele.mock.tool.MockValues;

public class UtilisateurEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public UtilisateurEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public UtilisateurEntity createInstance( Integer id ) {
		UtilisateurEntity entity = new UtilisateurEntity();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setNom( mockValues.nextString(255) ) ; // java.lang.String 
		entity.setMotdepasse( mockValues.nextString(255) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfAchat( TODO ) ; // List<Achat> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<UtilisateurEntity> createList(int count) {
		List<UtilisateurEntity> list = new LinkedList<UtilisateurEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
