/*
 * Created on 2 Nov 2017 ( Time 21:21:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package imta.modele.persistence.services.fake;

import java.util.List;
import java.util.Map;

import imta.modele.bean.jpa.AchatEntity;
import imta.modele.persistence.commons.fake.GenericFakeService;
import imta.modele.persistence.services.AchatPersistence;

/**
 * Fake persistence service implementation ( entity "Achat" )
 *
 * @author Telosys Tools Generator
 */
public class AchatPersistenceFAKE extends GenericFakeService<AchatEntity> implements AchatPersistence {

	public AchatPersistenceFAKE () {
		super(AchatEntity.class);
	}
	
	protected AchatEntity buildEntity(int index) {
		AchatEntity entity = new AchatEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		return entity ;
	}
	
	
	public boolean delete(AchatEntity entity) {
		log("delete ( AchatEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(AchatEntity entity) {
		log("insert ( AchatEntity : " + entity + ")" ) ;
	}

	public AchatEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<AchatEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<AchatEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<AchatEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public AchatEntity save(AchatEntity entity) {
		log("insert ( AchatEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<AchatEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
