/*
 * Created on 2 Nov 2017 ( Time 21:21:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package imta.modele.persistence.services.fake;

import java.util.List;
import java.util.Map;

import imta.modele.bean.jpa.UtilisateurEntity;
import imta.modele.persistence.commons.fake.GenericFakeService;
import imta.modele.persistence.services.UtilisateurPersistence;

/**
 * Fake persistence service implementation ( entity "Utilisateur" )
 *
 * @author Telosys Tools Generator
 */
public class UtilisateurPersistenceFAKE extends GenericFakeService<UtilisateurEntity> implements UtilisateurPersistence {

	public UtilisateurPersistenceFAKE () {
		super(UtilisateurEntity.class);
	}
	
	protected UtilisateurEntity buildEntity(int index) {
		UtilisateurEntity entity = new UtilisateurEntity();
		// Init fields with mock values
		entity.setId( nextInteger() ) ;
		entity.setNom( nextString() ) ;
		entity.setMotdepasse( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(UtilisateurEntity entity) {
		log("delete ( UtilisateurEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(UtilisateurEntity entity) {
		log("insert ( UtilisateurEntity : " + entity + ")" ) ;
	}

	public UtilisateurEntity load( Integer id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<UtilisateurEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<UtilisateurEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<UtilisateurEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public UtilisateurEntity save(UtilisateurEntity entity) {
		log("insert ( UtilisateurEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<UtilisateurEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

}
