/*
 * Created on 2 Nov 2017 ( Time 21:21:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package imta.modele.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "ARTICLE"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="ARTICLE", schema="ADMIN" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ArticleEntity.countAll", query="SELECT COUNT(x) FROM ArticleEntity x" )
} )
public class ArticleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NOM", nullable=false, length=255)
    private String     nom          ;

    @Column(name="DESCRIPTION", nullable=false)
    private String     description  ;

    @Column(name="QUANTITE", nullable=false)
    private Integer    quantite     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="article", targetEntity=AchatEntity.class)
    private List<AchatEntity> listOfAchat ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ArticleEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NOM ( VARCHAR ) 
    public void setNom( String nom ) {
        this.nom = nom;
    }
    public String getNom() {
        return this.nom;
    }

    //--- DATABASE MAPPING : DESCRIPTION ( LONG VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : QUANTITE ( INTEGER ) 
    public void setQuantite( Integer quantite ) {
        this.quantite = quantite;
    }
    public Integer getQuantite() {
        return this.quantite;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfAchat( List<AchatEntity> listOfAchat ) {
        this.listOfAchat = listOfAchat;
    }
    public List<AchatEntity> getListOfAchat() {
        return this.listOfAchat;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(nom);
        // attribute 'description' not usable (type = String Long Text)
        sb.append("|");
        sb.append(quantite);
        return sb.toString(); 
    } 

}
