/*
 * Created on 3 Nov 2017 ( Time 09:39:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package imta.modele.test.persistence;


import imta.modele.bean.jpa.AchatEntity;
import imta.modele.mock.AchatEntityMock;
import imta.modele.persistence.PersistenceServiceProvider;
import imta.modele.persistence.services.AchatPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Achat persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class AchatPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		AchatPersistence service = PersistenceServiceProvider.getService(AchatPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Achat persistence : delete + load ..." );
		
		AchatPersistence service = PersistenceServiceProvider.getService(AchatPersistence.class);
		
		AchatEntityMock mock = new AchatEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(AchatPersistence service, AchatEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		AchatEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Article
			// . Utilisateur
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
