/*
 * Created on 2 Nov 2017 ( Time 21:21:30 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package imta.modele.test.persistence;


import imta.modele.bean.jpa.ArticleEntity;
import imta.modele.mock.ArticleEntityMock;
import imta.modele.persistence.PersistenceServiceProvider;
import imta.modele.persistence.services.ArticlePersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Article persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class ArticlePersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		ArticlePersistence service = PersistenceServiceProvider.getService(ArticlePersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test Article persistence : delete + load ..." );
		
		ArticlePersistence service = PersistenceServiceProvider.getService(ArticlePersistence.class);
		
		ArticleEntityMock mock = new ArticleEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 1  );
		// process( service, mock, ... );
	}

	private void process(ArticlePersistence service, ArticleEntityMock mock, Integer id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		ArticleEntity entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
